version: '3'
services:
  guacd:
    image: guacamole/guacd
    networks:
      - guac-network

  guacamole:
    image: guacamole/guacamole
    environment:
      GUACD_HOSTNAME: guacd
    ports:
      - "8080:8080"
    depends_on:
      - guacd
    networks:
      - guac-network

networks:
  guac-network: